services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    # env_file:
    #   - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./backend/Dockerfile
  #   container_name: money-tracker-backend
  #   restart: unless-stopped
  #   # env_file:
  #   #   - ./backend/.env
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #   ports:
  #     - "${BACKEND_PORT:-8080}:8080"
  #   # depends_on:
  #   #   postgres:
  #   #     condition: service_healthy
  #   # healthcheck:
  #   #   test:
  #   #     [
  #   #       "CMD",
  #   #       "wget",
  #   #       "--no-verbose",
  #   #       "--tries=1",
  #   #       "--spider",
  #   #       "http://localhost:8080/health",
  #   #     ]
  #   #   interval: 30s
  #   #   timeout: 10s
  #   #   retries: 3
  #   #   start_period: 40s

volumes:
  postgres_data:
    driver: local
