# # ConfigMap
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nextjs-config
#   labels:
#     app: nextjs-app
# data:
#   NEXT_PUBLIC_API_URL: "http://localhost:3000/api"
#   NEXT_PUBLIC_APP_NAME: "My Next.js App"