---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: money-tracker
type: Opaque
stringData:
  POSTGRES_DB: "moneytracker"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "Bx8Q!56=Ums"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: money-tracker
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "Bx8Q!56=Ums"
  POSTGRES_DB: "moneytracker"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  labels:
    app: money-tracker
type: Opaque
stringData:
  NEXT_PUBLIC_API_URL: "http://backend-service"
---